namespace NodeJS {
  export interface ProcessEnv {
    KINDE_SITE_URL,
    STRIPE_STARTUP_PRICE_ID,
    STRIPE_ENTERPRISE_PRICE_ID,
    NEXT_PUBLIC_STRIPE_ENTERPRISE_PRICE_ID,
    NEXT_PUBLIC_STRIPE_STARTUP_PRICE_ID
  }
}