export const plans = [
  {
    name: 'Freelancer',
    id: 'plan-freelancer',
    href: '/dashboard',
    price: { monthly: 'Grátis', yearly: 'Grátis' },
    description: 'Perfeito para começar seu blog.',
    features: [
      '1 blog',
      '200 artigos',
      '2.000 visualizações/mês',
      'Domínio padrão',
      'I.A. com sua chave de API',
      'Tópicos pré-definidos',
      'API básica (100 requisições/mês)',
    ],
    mostPopular: false,
    buttonText: 'Aproveite seu plano',
  },
  {
    name: 'Startup',
    id: process.env.NEXT_PUBLIC_STRIPE_STARTUP_PRICE_ID,
    price: { monthly: 'US$1', yearly: 'US$12' },
    description: 'Ideal para blogs em crescimento.',
    features: [
      '2 blogs',
      '1.200 artigos',
      '20.000 visualizações/mês',
      'Domínio personalizado',
      'I.A. com sua chave de API',
      'I.A. nativa (1.000 requisições/mês)',
      'Sistema de comentários e likes',
      'Login social',
      'Criação de tópicos personalizados',
      'API completa (1.000 requisições/mês)',
    ],
    mostPopular: true,
    buttonText: 'Assinar',
  },
  {
    name: 'Empresarial',
    id: process.env.NEXT_PUBLIC_STRIPE_ENTERPRISE_PRICE_ID,
    price: { monthly: 'US$6', yearly: 'US$72' },
    description: 'Recursos avançados para grandes operações de blog.',
    features: [
      'Blogs ilimitados',
      'Artigos ilimitados',
      'Visualizações ilimitadas',
      'Domínio personalizado',
      'I.A. com sua chave de API',
      'I.A. nativa ilimitada',
      'Sistema de comentários avançado',
      'Login social e SSO',
      'Gerenciamento avançado de tópicos',
      'API ilimitada com suporte prioritário',
      'Análise de engajamento',
      'Sistema de assinantes e newsletter',
      'Automações de marketing',
      'Integrações e Webhooks',
    ],
    mostPopular: false,
    buttonText: 'Assinar',
  },
];